name: tests

on:
    push: { branches: [ master, main ] }
    pull_request: ~
    
jobs:
    run:
        name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
        runs-on: ${{ matrix.operating-system }}
        strategy:
            matrix:
                operating-system: [ ubuntu-latest ]
                php-versions: [ '8.0', '8.1' ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
                    extensions: mbstring

            -   name: Composer dependencies
                run: composer install --no-progress --prefer-dist --optimize-autoloader

            -   name: "PHPUnit"
                run: ./vendor/bin/phpunit tests

            -   name: "PHPStan"
                run: ./vendor/bin/phpstan analyze -l 8 src
